all:
	g++ -std=c++20 -fopenmp -pthread -o task3_1 task3_1.cpp
	g++ -std=c++20 -pthread -o task3_2 task3_2.cpp
	g++ -std=c++20 -pthread -o task3_2_test task3_2_test.cpp
clean:
	rm -f task3_1 task3_2 task3_2_test